name: Compiler testing

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-compile:
    runs-on: ${{ matrix.os }}
    env:
      CXXSTD: ${{ matrix.cpp_std }}
      CXXFLAGS: ${{ startsWith(matrix.compiler, 'gcc') && '-Wp,-D_GLIBCXX_ASSERTIONS' || ''}}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        compiler:
          - 'clang-12'
          - 'gcc-11'
        cpp_std:
          - 'c++11'
          - 'c++14'
          - 'c++17'
          - 'c++20'
        include:
          # Add os_name
          - os: ubuntu-20.04
            os_name: focal
          # macOS builds
          - os: macos-13
            compiler: 'clang'
            cpp_std: 'c++11'
          - os: macos-13
            compiler: 'clang'
            cpp_std: 'c++17'
          # Limited testing for older compilers
          - os: ubuntu-20.04
            os_name: focal
            compiler: 'clang-11'
            cpp_std: 'c++11'
          - os: ubuntu-20.04
            os_name: focal
            compiler: 'gcc-10'
            cpp_std: 'c++11'
      fail-fast: false
    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install gperf build-essential bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install bison flex gawk libffi pkg-config bash

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Linux runtime environment
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH
          echo "procs=$(nproc)" >> $GITHUB_ENV

      - name: macOS runtime environment
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
          echo "procs=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

      - name: Tool versions
        shell: bash
        run: |
          $CC --version
          $CXX --version

      - name: Checkout Yosys
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          make config-${CC%%-*}
          make -j$procs CXXSTD=$CXXSTD CC=$CC CXX=$CXX LD=$CC

      - name: Log yosys-config output
        run: |
          ./yosys-config || true
